# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-hello-world',
                'doc_host': 'https://mkram.github.io',
                'git_url': 'https://github.com/mkram/nbdev-hello-world',
                'lib_path': 'nbdev_hello_world'},
  'syms': { 'nbdev_hello_world.core': {'nbdev_hello_world.core.foo': ('mycore.html#foo', 'nbdev_hello_world/core.py')},
            'nbdev_hello_world.mycore': { 'nbdev_hello_world.mycore.HelloSayer': ('mycore.html#hellosayer', 'nbdev_hello_world/mycore.py'),
                                          'nbdev_hello_world.mycore.HelloSayer.__init__': ( 'mycore.html#hellosayer.__init__',
                                                                                            'nbdev_hello_world/mycore.py'),
                                          'nbdev_hello_world.mycore.HelloSayer.say': ( 'mycore.html#hellosayer.say',
                                                                                       'nbdev_hello_world/mycore.py'),
                                          'nbdev_hello_world.mycore.foo': ('mycore.html#foo', 'nbdev_hello_world/mycore.py'),
                                          'nbdev_hello_world.mycore.say_hello': ('mycore.html#say_hello', 'nbdev_hello_world/mycore.py')}}}
